### PR TITLE
fix : run ci in multi env os

### LINKED ISSUE #293: Write Github CI script to test according to environment
**What would you like to be added**:
Workflow that automatically tests according to the environment (windows, ubuntu, macOS) when PR comes in.

**Why is this needed**:
It's easy to manage PR effectively because the maintainer can't run it and test it, depending on the environment.

### PR DESCRIPTION
**Pull request by Limm-jk**
**What this PR does / why we need it**:
- Workflow that automatically tests according to the environment (windows, ubuntu, macOS) when PR comes in.
- coverage has uploaded in ubuntu env

**Which issue(s) this PR fixes**:

Fixes #293 

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
github actions will be run like below screenshot

```
image

**Additional documentation**:

```docs

```

**Checklist**:
- [ ] Added relevant tests or not required
- [ ] Didn't break anything

### CODE REVIEW

**Review by sinkyoungdeok — COMMENTED** [review]
https://github.com/yorkie-team/yorkie/blob/b5321a49607ec6c52f7d46594cb7f16a0ebd41c9/pkg/locker/locker.go#L32

enter is needed here for lint resolution

**Comment by Limm-jk** [comment]
@sinkyoungdeok Thank you! but it's valid pattern. [ref.](https://github.com/golang/go/wiki/CodeReviewComments#package-comments) we dont have to add new line on this failed line.

**Comment by Limm-jk** [comment]
i dont know why lint was failed only windows env.

**Comment by blurfx** [comment]
It seems to be related to this issue: mgechev/revive#607

**Comment by hackerwins** [comment]
I think it would be good to close this PR for now and open it later when working again.

**Pull request closed without merging**
