### PR TITLE
Update go version (1.16)

### LINKED ISSUE #157: Update to version Go 1.16
**Description**:

[Go 1.16](https://golang.org/doc/go1.16) has recently been released. We need to check about changes from 1.13 to 1.16 and reflect the changes on the Yorkie.

**Why**:

We can reflect on the latest Go improvements and keep an up-to-date code.

### PR DESCRIPTION
**Pull request by dc7303**
**What this PR does / why we need it**:
We recommend the latest version of `Go`, so we will update it.

**Which issue(s) this PR fixes**:

Fixes #157

**Special notes for your reviewer**:
Since `ioutil` is deprecated, I modified the code that uses that package.
https://golang.org/doc/go1.16#ioutil

**Does this PR introduce a user-facing change?**:

```release-note

```

**Additional documentation**:

```docs

```

**Checklist**:
- [x] Added relevant tests or not required
- [x] Didn't break anything

### CODE REVIEW

**Review by hackerwins — COMMENTED** [review]
@dc7303 Thanks for the contribution. I have a question.
Do we have to update Go version in README.md?

**Comment by dc7303** [comment]
@hackerwins That's a good point!
We need 1.16 or higher as we change ioutil to io package. So, REAMDE.md update is also required.

But before proceeding with the update, I would like to make a suggestion.
Since the minimum go version is specified in go.mod, how about removing the go version information from REAMDE.md?

**Comment by hackerwins** [comment]
@dc7303 
Thanks for the comments. I think you gave me a suggestion because of the idea that it is redundant.
However, I think it's okay to specify the version as it is easy for new developers to get started. If it's still a problem the next time the Go version is updated, it might be okay to remove it.

**Comment by dc7303** [comment]
@hackerwins 
Thanks for your good opinion! 😄 
The `README.md` has been updated, and the configuration files in `workflows` have also been updated.

**Review by hackerwins — APPROVED** [review]
LGTM.

**Pull request merged**
