### PR TITLE
Add customizable metadata for peer awareness

### PR DESCRIPTION
**Pull request by habibrosyad**
**What type of PR is this?**
/kind api-change
/kind feature

**What this PR does / why we need it**:
Add customizable metadata for peer awareness. Currently the API only exposes client ID and there's no way to add extra information about the client during collaborative activities.

**Which issue(s) this PR fixes**:
Fixes https://github.com/yorkie-team/yorkie-js-sdk/issues/106
Related with https://github.com/yorkie-team/yorkie/issues/48

**Special notes for your reviewer**:
This works around `WatchDocuments` rpc call. In the `WatchDocumentsRequest` I add a new meta field, where you could put whatever peer's metadata there. The metadata then passed along with the `WatchDocumentsResponse`.

**Does this PR introduce a user-facing change?**:

```release-note

```

**Additional documentation**:

```docs

```

### CODE REVIEW

**Review by dc7303 — COMMENTED** [review]
Thank you very much for doing a great job! 👍 
I reviewed this PR along with the yorkie-team/yorkie-js-sdk#110 PR. And I tested it and confirmed that it works fine.

I would like to see this wonderful PR and give you some opinions. And I need your feedback :)

We provide `Client` in `Yorkie`. And `Client` can subscribe to events like `yorkie-js-sdk` using `Watch`. So, in accordance with the progress of the yorkie-team/yorkie-js-sdk#110 PR, I hope that the modification of `Client` will proceed in this PR as well. If this happens, I think we can clearly define the test case for this feature.
And when this PR is complete, I would like to review on yorkie-team/yorkie-js-sdk#110.

What do you think? Please tell us your honest opinion.

**Comment by habibrosyad** [comment]
@dc7303 I think I missed the Go client in this repo. Sure, I will update this PR with that as well.

**Comment by habibrosyad** [comment]
@dc7303 @hackerwins I noticed that yorkie-js-sdk is not exposing the [EventType](https://github.com/yorkie-team/yorkie/blob/master/api/yorkie.proto#L356-L360) as described in the proto for client's subscription but using a custom defined [ClientEventType](https://github.com/yorkie-team/yorkie-js-sdk/blob/master/src/core/client.ts#L57-L63). 

On the other hand, the [WatchResponse](https://github.com/yorkie-team/yorkie/blob/master/client/client.go#L264-L268) in the Go client uses EventType. Therefore, somehow the event exposes by these two clients is different. Is it intended?

**Comment by hackerwins** [comment]
@habibrosyad 

It seems that all of the features are not implemented in the Go client yet. As more features are implemented in the JS SDK, I think we should also implement ClientEventType in Go Client.

**Comment by hackerwins** [comment]
We will continue this at #138.

**Comment by habibrosyad** [comment]
@hackerwins thanks for continuing the work. Got busy these days, so haven't had a chance to complete this PR.

**Comment by hackerwins** [comment]
@habibrosyad No worries. This PR allows us to add useful features to our users. Thank you.

**Pull request closed without merging**
