### PR TITLE
Add consistency test for ClientInfo update failure in PushPull

### PR DESCRIPTION
**Pull request by sejongk**
**What this PR does / why we need it**:
This PR adds a consistency test for the scenario where updating `ClientInfo` fails during `PushPull`.

**Which issue(s) this PR fixes**:

Related to #1001 

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note

```

**Additional documentation**:

```docs

```

**Checklist**:
- [x] Added relevant tests or not required
- [x] Didn't break anything

## Summary by CodeRabbit

- **New Features**
	- Updated the dependency to the latest version, potentially enhancing application performance and stability.
	- Introduced a mock database for testing, allowing for simulated database interactions without affecting actual data.

- **Tests**
	- Added a comprehensive suite of tests for the `packs` module, validating document change consistency and error handling scenarios.

### CODE REVIEW

**Comment by kokodak** [comment]
Related to #1001 .

**Comment by sejongk** [comment]
@hackerwins @kokodak 
I applied mocking to the test code and marked the test as skipped as a TODO.
Can you please review the changes?

**Review by kokodak — COMMENTED** [review]
The test code looks to be well written!

However, there seems to be some problems with the current MockDB as follows:

1. When there is a change in the Database interface, MockDB does not satisfy the Database interface, which is easily broken.
2. Although it is MockDB, the remaining methods are not stubbable except for the UpdateClientInfoAfterPushPull method.

**To properly address this, I've been considering two solutions as follows:**

1. Embed the Database interface inside the MockDB struct, inject the MongoDB implementation externally, and override only the methods that require stubbing. In this case, I think we can stub only the necessary methods while minimising the boilerplate code.
2. Use [Mockery](https://github.com/vektra/mockery) to automatically generate mocks for the Database interface, and put the actual DB logic needed by the test inside the stubbing logic. In this case, I think partial mocking would be possible.

In my opinion, I think option 1 would be a good way to improve the problem, because it doesn't rely on external libraries and minimises boilerplate code.

**Review by hackerwins — APPROVED** [review]
Thanks for your contribution.

**Pull request merged**
