### PR TITLE
Use multi-stage build for docker image

### PR DESCRIPTION
**Pull request by habibrosyad**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespace from that line:
>
> /kind api-change
> /kind bug
> /kind cleanup
> /kind deprecation
> /kind design
> /kind documentation
> /kind failing-test

/kind feature

**What this PR does / why we need it**:
- Use multi-stage docker build for smaller image size ( < 30MB )
- Overridable config file via mounting path to `/config.json`

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation**:

```docs

```

### CODE REVIEW

**Comment by hackerwins** [comment]
@habibrosyad Thanks for contributing. We'll review this soon.

**Comment by hackerwins** [comment]
Thanks for contributing. I'm happy to know how to optimize the image.

I looked for `golang:<version>-alpine`. And I've seen the [DockerHub docs mention](https://hub.docker.com/_/golang?tab=description&page=1&ordering=last_updated) it as a highly experimental image. And I have two questions.

- Are there any cases of using this pattern in other projects?
- Will it benefits users to think about image optimization at this time?

**Comment by habibrosyad** [comment]
@hackerwins to answer the questions:
1. It is a common pattern and is well [documented in Docker](https://docs.docker.com/develop/develop-images/multistage-build/). For a sample project here's one from [TiKV](https://github.com/tikv/tikv/blob/master/Dockerfile).

2. With the reduces in image sizes it certainly will benefit users when pulling the image (especially on slow connections). Personally, I'm thinking that this optimization is not that urgent right now, but it wont hurt either if it's introduced early.

For the alpine image, I just realised that it's still experimental for Golang. I usually used that base and have no problem till now. But just to make sure no issues in the future, I'm thinking of updating this PR with buster base image.

**Review by dc7303 — APPROVED** [review]
While reviewing this PR, I looked at the multi-stage build.
And it was confirmed that a lot of weight reduction can be obtained.

My guess is, if we use `golang-buster`, applying this pattern now doesn't seem to be a problem.
LGTM 👍 Thanks for the great work.

**Review by hackerwins — APPROVED** [review]
LGTM.  Thank you. I noticed that the image is changed very lightly.

```
yorkieteam/yorkie                              0.1.1               0bda3dbae22f        21 seconds ago      92.5MB // debian:buster-slim
yorkieteam/yorkie                              0.1.0               67a838e61495        3 weeks ago         1.5GB // golang:latest
```

**Comment by hackerwins** [comment]
@habibrosyad The image size has been reduced thanks to your contribution. Thank you.
Screen Shot 2021-01-01 at 8 37 42 PM

**Comment by habibrosyad** [comment]
@hackerwins no worries. My thanks also for this wonderful project 👍 Looking forward to contribute more.

**Pull request merged**
