### PR TITLE
Clear presence when housekeeping process

### LINKED ISSUE #602: Handle Presence Cleanup in Housekeeping Process
**Description**: 

When a document is explicitly detached, the presence is removed from the presences through `PresenceChange{type: 'clear'}`. This helps keep snapshot presence lightweight. However, when the client does not explicitly invoke detach, there is an issue that the presence not to be cleared.

Currently, during housekeeping, the document state is updated using `clientInfo.DetachDocument()`. It is also necessary to clear the presence at this point.

https://github.com/yorkie-team/yorkie/blob/65c8164a981dfed312e7f98cff174203e44674cd/server/backend/housekeeping/housekeeping.go#L171-L177

https://github.com/yorkie-team/yorkie/blob/65c8164a981dfed312e7f98cff174203e44674cd/server/clients/clients.go#L72-L80

**Why**:
To prevent continuous growth of the presence snapshot.

### PR DESCRIPTION
**Pull request by raararaara**
#### What this PR does / why we need it?

This PR addresses the absence of presence clearing logic in document detach during client deactivation for Housekeeping compared to document detach by the SDK. By implementing server-side presence clearance, this PR ensures that presence is correctly handled during the housekeeping process.

#### Any background context you want to provide?

The changes include:
1) Performing document detach with client deactivation and updating the SyncedSeq solely through the database -> making an API call similar to the SDK's document detach
This change allows presence to be cleared through `client.detach()` during deactivation and detach processes, simplifying the process and omitting the need for updating SyncedSeq separately. 
In case of deactivation failure, some documents may not detach completely, but another deactivation attempt is possible.
2) Consideration for clustering and sharding per document
Taking into account document structures sharded across clusters by keys, the update allows one server to act as a client while multiple servers can perform detach operations.

#### What are the relevant tickets?

Fixes #602 

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note

```

**Additional documentation**:

```docs

```

**Checklist**:
- [x] Added relevant tests or not required
- [x] Didn't break anything

## Summary by CodeRabbit

- **New Features**
  - Introduced methods for simulating document attachment and client activation, enhancing server-side operations.
  - Added functionality for converting internal documents to public documents, improving document management.
  - Enhanced client connection capabilities, allowing for improved document and client interaction.
  - Implemented configuration options for dynamic gateway service referencing in Kubernetes.
  - Added command-line flags for backend gateway address configuration, increasing server flexibility.

- **Bug Fixes**
  - Improved error handling for detach requests to ensure system integrity in case of failures.
  - Enhanced logic for client deactivation, ensuring the most up-to-date client state is utilized.

- **Chores**
  - Streamlined methods for client deactivation, simplifying document status management during operations.
  - Expanded configuration options in the Helm chart for better service adaptability.
  - Added new constants and configuration fields to improve server setup and management.

### CODE REVIEW

**Review by hackerwins — COMMENTED** [review]
Thanks for your contribution. Overall looks good.

I have a few questions:

## A. Configuration and Management Consistency Issue

The `rpcAddr` is injected via a flag, then managed through config, and finally injected as an argument to the function where it's used. In contrast, the `gateway address` is injected via an environment variable. There appears to be a lack of consistency in configuration management and usage. Is there a good solution for this?

## B. Reason for Authentication Token

When the Housekeeping node requests a Detach operation from the cluster, it uses an Authorization token. Is there any reason for this?

## C. Detach Delegation

The Yorkie cluster implements Consistent Hashing using Istio, with specific nodes responsible for specific Documents. The node running Housekeeping needs to delegate the Detach operation to the node responsible for the Document. To achieve this, the Housekeeping node uses the Gateway address to call Detach, thus distributing the load.

@krapie 

I'm curious about your opinion on whether this method is appropriate.

**Comment by raararaara** [comment]
@hackerwins 

The answer to question B is:

During the deactivate process, the `VerifyAccess()` was performed, and a test case that failed was found during this process, such as [authorization webhook test](https://github.com/yorkie-team/yorkie/blob/e1fbcf34d700f756934dd5ae8932353d4f536885/test/integration/auth_webhook_test.go#L92-L141).

For the remaining questions, I look forward to hearing ideas from others.

**Comment by krapie** [comment]
@hackerwins I think current approach is fare enough because we need to go through yorkie-gateway to delegate the operation. I'm wondering what will happen when detach is not performed on other documents that user was attached, and then deactivation occurs?

**Comment by raararaara** [comment]
@krapie Could you please explain in more detail what you are curious about?

Are you referring to a situation where document detach fails and only client deactivate occured during the process of client deactivation, specifically `clients.deactivate()`?

**Comment by raararaara** [comment]
I have identified an issue related to Authorization as pointed out by @hackerwins . Specifically, the issues are as follows:

- For clients with a token value, the `verifyAccess` process is required during `deactivate` or `detach`.
  - When receiving a `deactivate` or `detach` request from an external source, the client's token value is passed along with the request.
  - However, in cases where a client is temporarily created during the server (Housekeeping) process, there is no way to know this token value.

To address this issue, I'm considering the following two actions:

1. **Issuing a Server-Specific Token**:  
   We plan to generate a shared token for all servers, allowing us to skip the `verifyAccess` step for server-specific tokens. We are considering methods such as injecting this token through the `defaultFlag` or a DevOps manifest.

2. **Defining a `systemService`**:  
   Currently, only `rpcService` and `adminService` are defined. We propose defining a new `systemService` to separate the logic for inter-server communication from existing services.

---
Given the additional work required, I will mark this PR as a draft.

And of course, any feedback or comments are welcome!

**Comment by krapie** [comment]
@raararaara My apologizes, I was asking the wrong question.

**Comment by hackerwins** [comment]
This PR continues in #1036.

**Pull request closed without merging**
