### PR TITLE
Modify yorkie-cluster helm chart k8s version (1.24 => 1.23)

### PR DESCRIPTION
**Pull request by emplam27**
**What this PR does / why we need it**:

- Modify yorkie-cluster helm chart k8s version (1.24 => 1.23)

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note

```

**Additional documentation**:

```docs

```

**Checklist**:
- [x] Added relevant tests or not required
- [x] Didn't break anything

### CODE REVIEW

**Review by krapie — COMMENTED** [review]
Can I get an explanation of why this change is needed?

**Comment by emplam27** [comment]
> Can I get an explanation of why this change is needed?

we want to use 'n3r Dedicated Cluster' to deploy yorkie with the same helm configuration in naver internal environment. 
1.23 version is required to use n3r Dedicated Cluster.

**Review by krapie — APPROVED** [review]
@emplam27 
I have looked up for changes between v1.24 and v1.23 with Istio 1.17, and also tested yorkie cluster on v1.23 environment.
It seems okay to downgrade K8s version to v1.23.

**Comment by hackerwins** [comment]
@krapie Thank you for checking compatibility.

**Pull request merged**
