### PR TITLE
Migrate RPC to ConnectRPC

### LINKED ISSUE #668: Research connect-rpc
**Description**:

There is an alternative to `grpc-web` called [connect-web](https://buf.build/blog/connect-web-protobuf-grpc-in-the-browser). We've been struggling a bit with grpc-web(not providing bidirectional, forcing Envoy, etc...).

The following might be considered together:

- Can it be work with [gogo/protobuf](https://github.com/gogo/protobuf)?
- Can we remove Envoy from the server for the web?
- Are all APIs working normally after replacing with connect-web?
- Does it provide bi-directional communication?

Let's research connect-web.

**Why**:
- It might work around the limitations of grpc-web.

### PR DESCRIPTION
**Pull request by krapie**
**What this PR does / why we need it**:

Migrate RPC to [ConnecRPC](https://connectrpc.com/).

ConnectRPC supports following features:
- Supports interoperation and multiplexing of `grpc`, `grpc-web`, and `Connect` protocols.
- Supports language-familiar primitives like `net/http` and `fetch`.
- Supports simple and no-boilerplate codes.

With this support, you can resolve several issues:
- Removes dependency with Envoy proxy to communicate with JS SDK web client by [grpc-web](https://github.com/grpc/grpc-web).
- Removes dependency with deprecated [gogo/protobuf](https://github.com/gogo/protobuf).
- Supports JSON based REST API which will satisfy [these needs](https://github.com/yorkie-team/yorkie/issues/677).

**Which issue(s) this PR fixes**:

Related to #668

**Special notes for your reviewer**:

> [!NOTE]
> After merging this PR, I will remove envoy proxy on docker configuration on other repositories too.

> [!NOTE]
> JS SDK compatibility: Since `connect-go` does not support `grpc-web-text` which current JS SDK gRPC-web client uses, we need to migrate JS SDK's RPC to ConnectRPC as well. We can temporary change JS SDK's docker-compose settings (keep envoy proxy and change server rpc port to `11101`) to support compatibility with ConnectRPC server and JS SDK gRPC-web client before finishing migration of ConnectRPC on JS SDK.

> [!NOTE]
> Server configuration: We need to find corresponding `net/http` server configurations that matches with `gRPC` server options such as `MaxRequestBytes`, `MaxConnectAge` and `MaxConnectionAgeGrace`. Because of this issue, `watch document test` is temporary commented.

> [!NOTE]
> gRPC Metrics: Since we cannot use `go-grpc-prometheus` that measured gRPC server metrics, I have implemented RPC metrics by referencing `go-grpc-prometheus`. Because the syntax of newly implemented metrics are different from `go-grpc-prometheus`, we also need to update Grafana query (ex: `grpc_server_handled_total` to `yorkie_rpc_server_handled_total`, `grpc_type` to `rpc_type`).

> [!NOTE]
> Since we no longer have Envoy proxy to handle CORS, I have implemented CORS on RPC server. But for cluster mode, we have ingressgateway to handle CORS. So we need to implement disable option for CORS on server.

**Does this PR introduce a user-facing change?**:

```release-note
- Server port has been changed to `8080` from `11101` for RPC port, and `8081` from `11102` for profiling port.
- User can now also send HTTP requests and receive JSON response. For example:
  curl -X POST \
      --url http://localhost:8080/yorkie.v1.AdminService/GetDocument \
      --header "Content-Type: application/json" \
      --header "Authorization: eyJBDB...." \
      --data '{"project_name": "default", "document_key": "codemirror"}
```

**Additional documentation**:

```docs

```

**Checklist**:
- [x] Added relevant tests or not required
- [x] Didn't break anything

### CODE REVIEW

**Comment by hackerwins** [comment]
@7hong13, @humdrum

Before merging this PR, we need to ensure that mobile SDKs can communicate with the server. Yorkie Go Server already multiplexes the existing grpc protocol, we expect no issues.

**Comment by chacha912** [comment]
When testing on the dashboard, the following error occurs:

**Comment by krapie** [comment]
@chacha912 This is because dashboard also uses `grpc-web-text` format which ConnectRPC server does not support.
We also need to update dashboard's RPC to ConnectRPC, just like JS SDK.

**Comment by hackerwins** [comment]
Related to https://github.com/yorkie-team/dashboard/issues/42

**Review by hackerwins — APPROVED** [review]
Thanks for your contribution.

**Pull request merged**
